<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mageUrl = $storeManager->getStore()->getBaseUrl();
?>

<div class="admin__data-grid-pager" style="float: right;
    padding-bottom: 10px;display:none;" id="paginationDiv">
    <button class="action-previous" type="button"  title="Previous Page" id="prevBtn"></button>
    <input class="admin__control-text" type="number" data-ui-id="current-page-input" id="curPage" value="1" onchange="goPage()">
    <label class="admin__control-support-text" id="totalPage"></label>
    <button class="action-next" type="button" title="Next Page" id="nextBtn"></button>
</div>
<table id="grid-data" class="data-grid data-grid-draggable">
    <thead>
        <th class="data-grid-th">Name</th>
        <th class="data-grid-th">Sku</th>
        <th class="data-grid-th">Total Qty</th>
        <th class="data-grid-th">Available Qty</th>
        <th class="data-grid-th">Qty in Pending</th>
        <th class="data-grid-th">Qty in Processing</th>
        <th class="data-grid-th">Qty in Complete</th>
    </thead>
    <tbody></tbody>
    
</table>
<script>
curPage=1;
dataCol = ['name','sku','qty_total','qty_available','qty_pending','qty_processing','qty_complete'];
document.getElementById('curPage').addEventListener("keydown", function (e) {
    if (e.keyCode === 13) {  //checks whether the pressed key is "Enter"
        loadData();
    }
});

loadData();
function loadData(curPage){
    
require([
    'jquery',
    "jquery/ui"
], function($){
    'use strict';
    
    $.ajax({
        url: "/internal_api/getStockStatus.php?page="+curPage, 
        success: function(result){
            $("#grid-data tbody tr").remove();
            loadTable(result);
            $("#grid-data").fadeOut();
            $("#grid-data").fadeIn("fast");
        }
    });
    
});
}
function addJavascript(jsname,pos) {
    var th = document.getElementsByTagName(pos)[0];
    var s = document.createElement('script');
    s.setAttribute('type','text/javascript');
    s.setAttribute('src',jsname);
    th.appendChild(s);
}

function loadTable(jsondata){
    curPage = document.getElementById('curPage').value;
    proObj = JSON.parse(jsondata);
   
    for(i=0;i<proObj.result.length;i++){
       
       tr = document.createElement('tr');
       for(j=0;j<dataCol.length;j++){
           td = document.createElement('td');
           td.innerHTML = proObj.result[i][dataCol[j]];
           if(j>1){
            td.style.textAlign='right';

           }
           td.style.borderBottom='1px solid lightgrey';
           tr.appendChild(td);
        }
        document.getElementById('grid-data').children[1].appendChild(tr);
    }
    if(curPage == 1){
        document.getElementById('prevBtn').disabled = true;

    }else{
        document.getElementById('prevBtn').disabled = false;
      
        document.getElementById('prevBtn').onclick = prevPage;
    }
    totalPage = Math.ceil(proObj.total/10);
    if(curPage == totalPage){
        document.getElementById('nextBtn').disabled = true;
    }else{
        document.getElementById('nextBtn').disabled = false;      

        document.getElementById('nextBtn').onclick = nextPage;
    }
    document.getElementById('totalPage').innerHTML='of '+totalPage;
    document.getElementById('paginationDiv').style.display = 'block';
    
}

function nextPage() {
    curPage = document.getElementById('curPage').value;
    curPage= parseInt(curPage)+1;
    loadData(curPage);
    document.getElementById('curPage').value=curPage;
}

function prevPage() {
    curPage = document.getElementById('curPage').value;
    curPage= parseInt(curPage)-1;
    loadData(curPage);
    document.getElementById('curPage').value=curPage;
}

function goPage(){
    curPage = document.getElementById('curPage').value;
    loadData(curPage);
   
}
</script>



